controller_list:
  - name: arm1_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm1_joint1
      - arm1_joint2
      - arm1_joint3
      - arm1_joint4
      - arm1_joint5
  - name: arm2_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - arm2_joint1
      - arm2_joint2
      - arm2_joint3
      - arm2_joint4
