controller_list:
  - name: fake_arm_1_controller
    joints:
      - arm1_joint1
      - arm1_joint2
      - arm1_joint3
      - arm1_joint4
      - arm1_joint5
  - name: fake_arm_2_controller
    joints:
      - arm2_joint1
      - arm2_joint2
      - arm2_joint3
      - arm2_joint4
  - name: fake_end_1_controller
    joints:
      - arm1_joint5
  - name: fake_end_2_controller
    joints:
      - arm2_joint4